sudo: false

language: python

python: 3.5

env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=py35
  - TOX_ENV=flake8

before_install:
  - pip install codecov

install:
  - pip install tox
  - pip install flake8

script:
  - tox -e $TOX_ENV

after_success:
  - codecov
