sudo: false

language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install pytest
  - pip install flake8
  - pip install pep8
  - pip install codecov
  - pip install tox
  - pip install .

script:
  - tox

after_success:
  - codecov
