sudo: false

language: python

python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - pip3 install pytest
  - pip3 install flake8
  - pip3 install pep8
  - pip3 install codecov

script:
  - tox

after_success:
  - codecov
